---

- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact: app_env="{{ lookup('env', 'APP_ENV') | default('staging', true) }}"
    - set_fact: app_port="{{ lookup('env', 'APP_PORT') | default('8080', true) }}"
    - set_fact: app_commit="{{ lookup('env', 'APP_COMMIT') | default('e229fdf8c6ae9885f35ec2cfb493ca22c7afb111', true) }}"

# Parallel building
# Lets build images inplace.
# Or we can fetch it from registry in real life.
- hosts: "{{ 'environment_' + hostvars.localhost.app_env }}"
  roles:
  - role: build_from_git
    image_name: "hello_app"
    git_url: "https://github.com/a0s/opstest.git"
    git_path: "hello_app_ruby"
    git_commit: "{{ hostvars.localhost.app_commit }}"

# Serial deploy
- hosts: "{{ 'environment_' + hostvars.localhost.app_env }}"
  serial:
  - 1
  - 5
  - 10
  roles:
  - role: deploy
    container_name: "hello_app"
    container_port: "{{ hostvars.localhost.app_port }}"
    service_name: "hello_app"
    image_name: "hello_app"
    image_tag: "{{ hostvars.localhost.app_commit }}"



