---

all:
  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: "{{ lookup('env','TF_VAR_aws_key_path_priv') }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
